package constant

import (
	"time"
)

const STATUS_WAITING_FOR_PRINTING = "STATUS_WAITING_FOR_PRINTING"
const STATUS_SUCCESSFUL_PRINTED = "STATUS_SUCCESSFUL_PRINTED"
const STATUS_WAITING_FOR_RETURN_PAGES = "STATUS_WAITING_FOR_RETURN_PAGES"
const STATUS_ERROR_WITH_PRINTING = "STATUS_ERROR_WITH_PRINTING"
const STATUS_WAITING_DOWNLOAD  = "STATUS_WAITING_DOWNLOAD"
const STATUS_WAITING_DELETE_FROM_TERMINAL  = "STATUS_WAITING_DELETE_FROM_TERMINAL"
const STATUS_PAGES_RETURNED  = "STATUS_PAGES_RETURNED"
const TIME_OVERSIGHT_FOR_PRINTING = time.Hour * 24 * 7
const TIME_RETIRED_OLD_FILE = time.Minute * 2
const TIME_OFTEN_REPEAT_ADD_NEW_FILE = time.Second * 2
const TIME_OFTEN_REPEAT_PRINT_FILE= time.Second * 2
const TIME_LAYOUT = "2006-01-02T15:04:05"

const ERROR_COOKIES  = "error_cookies"
const ERROR_SERVER = "error_server"
const ERROR_REQUEST = "error_request"
const ERROR_USER  =  "error_user"